# Generated by Django 6.0.6 on 2026-07-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('gravity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('notes', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='brewery.batch')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-measured_at'],
            },
        ),
    ]
