# Generated by Django 6.0.6 on 2026-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0002_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
