# Generated by Django 6.0.6 on 2026-07-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0003_alter_measurement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='raw_density',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Введенное значение'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.CharField(blank=True, choices=[('sg', 'SG'), ('brix', 'Brix')], default='sg', max_length=4, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='gravity',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Corrected SG'),
        ),
    ]
