# Generated by Django 6.0.6 on 2026-07-31 20:11

from django.db import migrations, models


def copy_gravity_data(apps, schema_editor):
    Measurement = apps.get_model('brewery', 'Measurement')
    for m in Measurement.objects.all():
        m.raw_density = m.gravity
        m.unit = 'sg'
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0003_alter_measurement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='raw_density',
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Density value'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.CharField(blank=True, choices=[(
                'sg', 'SG'), ('brix', 'Brix')], default='sg', max_length=4, null=True, verbose_name='Unit of measurement'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='gravity',
            field=models.DecimalField(
                decimal_places=3, max_digits=5, verbose_name='Corrected SG'),
        ),
        migrations.RunPython(copy_gravity_data, migrations.RunPython.noop),
    ]
