# Generated by Django 6.0.6 on 2026-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0004_measurement_raw_density_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='gravity',
            field=models.DecimalField(
                decimal_places=3, editable=False, max_digits=5, verbose_name='Corrected SG'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='raw_density',
            field=models.DecimalField(
                decimal_places=3, max_digits=5, verbose_name='Density value'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(choices=[('sg', 'SG'), ('brix', 'Brix')],
                                   default='sg', max_length=4, verbose_name='Unit of measurement'),
        ),
    ]
